name: s3-image-upload-thing

services:
  s3-upload-client:
    container_name: s3-upload-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args: 
        - NEXT_PUBLIC_API_URL: http://s3-upload-server:5101
        - NEXT_PUBLIC_S3_REGION: ap-southeast-2
    restart: unless-stopped
    depends_on:
      - s3-upload-server
    ports:
      - "5100:5100"

  s3-upload-server:
    container_name: s3-upload-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5101:5101"
