import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '@/css/globals.css'
import Providers from '@/lib/providers'

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  weight: ['100', '900'],
  fallback: ['Arial', 'sans-serif']
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  weight: ['100', '500', '900'],
  fallback: ['Arial', 'sans-serif']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <div className="min-h-screen w-screen grid grid-rows-[auto_1fr_auto]">
          <header className="bg-sky-600 text-center">Placeholder Header</header>
          <Providers>{children}</Providers>
          <footer className="bg-red-600 text-center">Placeholder Footer</footer>
        </div>
      </body>
    </html>
  )
}
