name: s3-image-upload-thing

services:
  s3-upload-client:
    container_name: s3-upload-client
    build:
      context: ../client
      dockerfile: ../.docker/client.Dockerfile
    restart: unless-stopped
    depends_on:
      - s3-upload-server
    environment:
      - NODE_ENV=production
      - API_URL=http://s3-upload-server:5101
      - NEXT_PUBLIC_S3_REGION=ap-southeast-2
      - PORT=5100
    ports:
      - "5100:5100"

  s3-upload-server:
    container_name: s3-upload-server
    build:
      context: ../server
      dockerfile: ../.docker/server.Dockerfile
    restart: unless-stopped
    env_file:
      - ../server/.env
    environment:
      - NODE_ENV=production
      - PORT=5101
    ports:
      - "5101:5101"
